[package]
name = "rsvp-saver"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "net", "macros"] }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "macros"] }
reqwest = { version = "0.12", features = ["json"], default-features = false }
tower-http = { version = "0.6", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
http = "1"
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["v4"] }
